services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    Denisok94\SymfonyExportXlsxBundle\:
        resource: '../../*'
        exclude: '../../{DependencyInjection,Resources,Writer}'

    
    # sonata.exporter.writer.xlsx:
    #     class: Denisok94\SymfonyExportXlsxBundle\Writer\XlsxWriter
    #     arguments: ["php://output"]
    #     tags:
    #         - { name: sonata.exporter.writer }