services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

        
    Denisok94\SymfonyExportXlsxBundle\:
        resource: '../../*'
        exclude: '../../{Admin,Controller,DependencyInjection,Entity,Event,Resources}'
